/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testQuotes() {
        Quotes[] quotes = new Quotes[];
        assertNotNull("app should have a greeting", quotes[0], Quotes.getQuote(quotes));
    }
}
