/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.util.Scanner;
import java.net.URL;

public class App {

    public static void main(String[] args) throws IOException {
        
//  Example:
//        {
//            "quoteText": "Peace cannot be kept by force. It can only be achieved by understanding.",
//                "quoteAuthor": "Albert Einstein",
//                "senderName": "",
//                "senderLink": "",
//                "quoteLink": "http://forismatic.com/en/1bbb4baea1/"
//        }

        getUrlQuote("http://swquotesapi.digitaljedi.dk/api/SWQuote/RandomStarWarsQuote");
    }

    public static void getFileQuote() throws IOException {
        String allQuotes = read("src/main/resources/recentquotes.json");
        Gson gson = new Gson();
        Quotes[] quotes = gson.fromJson(allQuotes, Quotes[].class );
        int random = (int)(Math.random() * quotes.length);
        System.out.println(quotes[random]);
    }

    public static void getUrlQuote(String quoteUrl) throws IOException {
        try {
            URL url = new URL(quoteUrl);

            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            BufferedReader reader = new BufferedReader(new InputStreamReader((con.getInputStream())));

            Gson gson = new Gson();
            ApiQuote randomQuote = gson.fromJson(reader, ApiQuote.class);
            System.out.println(randomQuote);
            write(randomQuote);

        } catch (MalformedURLException e) {
            System.out.println("exception: " + e);
            getFileQuote();
        }
    }

    public static String read(String fileName) throws IOException {
        Scanner sc = new Scanner(new File(fileName));
        StringBuilder strings = new StringBuilder();
        while(sc.hasNextLine()){
            strings.append(sc.nextLine());
        }
        return strings.toString();
    }

    public  static void write(ApiQuote t) throws IOException {
        Gson gson = new Gson();
        String gsonParsing = gson.toJson(t);

        BufferedWriter writer = new BufferedWriter(new FileWriter("src/main/resources/test.json", true));
        writer.newLine();
        writer.write(gsonParsing);
        writer.close();
    }
}